GET http://localhost:3000/todos/

###

GET http://localhost:3000/todos/623216827aea908cfec03384

###
POST http://localhost:3000/todos/
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMzIyMjhhMzM2MzMzM2E5M2U3MjVjOSIsImlhdCI6MTY0NzQ1MjgyMH0.Uk2d2HqPS_FxBVzVla-w7HAS-ngoITWYquCxekfFUXo

{
	"description": "This is a test"
}

###
PUT http://localhost:3000/todos/623216827aea908cfec03384
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjYxZWNhY2I4NDYwY2FjODNiOTVkNiIsImlhdCI6MTY0NjY2NTgyNn0.LwmcpeO8GUyLe-HdmqpbpClsHufhIxGt4SF3xjU-5XQ

{
	"description": "Editing test",
	"completed": true
}


###
DELETE http://localhost:3000/todos/622620968c8361f4ebf3996d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYyMjYxZWNhY2I4NDYwY2FjODNiOTVkNiIsImlhdCI6MTY0NjY2NTgyNn0.LwmcpeO8GUyLe-HdmqpbpClsHufhIxGt4SF3xjU-5XQ



